-- -- awesome_mode: api-level=4:screen=on
-- -- If LuaRocks is installed, make sure that packages installed through it are
-- -- found (e.g. lgi). If LuaRocks is not installed, do nothing.
-- pcall(require, "luarocks.loader")
-- 
-- -- Standard awesome library
-- local gears         = require("gears")
-- local awful         = require("awful")
-- -- require("awful.autofocus") -- [needed?]
-- -- Widget and layout library
-- local wibox         = require("wibox")
-- -- Theme handling library
-- local beautiful     = require("beautiful")
-- -- Notification library
-- local naughty       = require("naughty")
-- -- Declarative object management
-- local ruled         = require("ruled")
-- local menubar       = require("menubar")
-- local hotkeys_popup = require("awful.hotkeys_popup")
-- -- Enable hotkeys help widget for VIM and other apps
-- -- when client with a matching name is opened:
--                       require("awful.hotkeys_popup.keys")
-- 
-- -- {{{ Modules
-- local global = require("configs.global")
-- require("configs.widgets")
-- -- }}}
-- 
-- -- {{{ Variables
-- modkey = global.modkey
-- terminal = global.terminal
-- browser = global.browser
-- editor = global.editor
-- explorer = global.explorer
-- editor_cmd = global.editor_cmd
-- explorer_cmd = global.explorer_cmd
-- -- }}}
-- 
-- -- {{{ Wibar
-- -- Keyboard map indicator and switcher
-- mykeyboardlayout = awful.widget.keyboardlayout()
-- 
-- -- Create a textclock widget
-- mytextclock = wibox.widget.textclock()
--    
-- screen.connect_signal("request::desktop_decoration", function(s)
--     -- Each screen has its own tag table.
--     awful.tag({ "1", "2", "3", "4", "5", "6", "7", "8", "9" }, s, awful.layout.layouts[1])
-- 
--     -- Create a promptbox for each screen
--     s.mypromptbox = awful.widget.prompt()
-- 
--     -- Create an imagebox widget which will contain an icon indicating which layout we're using.
--     -- We need one layoutbox per screen.
--     s.mylayoutbox = awful.widget.layoutbox {
--         screen  = s,
--         buttons = {
--             awful.button({ }, 1, function () awful.layout.inc( 1) end),
--             awful.button({ }, 3, function () awful.layout.inc(-1) end),
--             awful.button({ }, 4, function () awful.layout.inc(-1) end),
--             awful.button({ }, 5, function () awful.layout.inc( 1) end),
--         }
--     }
-- 
--     -- Create a taglist widget
--     s.mytaglist = awful.widget.taglist {
--         screen  = s,
--         filter  = awful.widget.taglist.filter.all,
--         buttons = {
--             awful.button({ }, 1, function(t) t:view_only() end),
--             awful.button({ modkey }, 1, function(t)
--                                             if client.focus then
--                                                 client.focus:move_to_tag(t)
--                                             end
--                                         end),
--             awful.button({ }, 3, awful.tag.viewtoggle),
--             awful.button({ modkey }, 3, function(t)
--                                             if client.focus then
--                                                 client.focus:toggle_tag(t)
--                                             end
--                                         end),
--             awful.button({ }, 4, function(t) awful.tag.viewprev(t.screen) end),
--             awful.button({ }, 5, function(t) awful.tag.viewnext(t.screen) end),
--         }
--     }
-- 
--     -- Create a tasklist widget
--     s.mytasklist = awful.widget.tasklist {
--         screen  = s,
--         filter  = awful.widget.tasklist.filter.currenttags,
--         buttons = {
--             awful.button({ }, 1, function (c)
--                 c:activate { context = "tasklist", action = "toggle_minimization" }
--             end),
--             awful.button({ }, 3, function() awful.menu.client_list { theme = { width = 250 } } end),
--             awful.button({ }, 4, function() awful.client.focus.byidx(-1) end),
--             awful.button({ }, 5, function() awful.client.focus.byidx( 1) end),
--         }
--     }
-- 
--     -- Create the wibox
--     s.mywibox = awful.wibar {
--         position = "top",
--         screen   = s,
--         widget   = {
--             layout = wibox.layout.align.horizontal,
--             { -- Left widgets
--                 layout = wibox.layout.fixed.horizontal,
--                 s.mylayoutbox,
--                 -- mylauncher,
--                 -- s.mytaglist,
--                 s.mypromptbox,
--             },
--             { -- Center widgets
--                 layout = wibox.layout.fixed.horizontal,
--                 s.mytaglist, -- Middle widget
--             },
--             { -- Right widgets
--                 layout = wibox.layout.fixed.horizontal,
--                 -- mykeyboardlayout,
--                 wibox.widget.systray(),
--                 mytextclock,
--                 -- s.mylayoutbox,
--             },
--         }
--     }
-- end)
-- -- }}}
