#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
picom &
feh --bg-fill ~/Pictures/Wallpapers/SynthPyramids.jpg &
$HOME/.config/polybar/launch.sh

#bspc monitor -d 一 二 三 四 五 六 七 八 九 十
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width           2
bspc config window_gap             7

bspc config split_ratio            0.5
bspc config borderless_monocle     false
bspc config gapless_monocle        false
bspc config normal_border_color    "#BD93F9"
bspc config active_border_color    "#FF79C6"
bspc config focused_border_color   "#FFB86C"
bspc config presel_feedback_color  "#8BE9FD"
bspc config presel_feedback        true

bspc rule -a Gimp desktop='^8' state=floating follow=on
