#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
picom &
#feh --background-fill ~/Pictures/Wallpapers/ &
$HOME/.config/polybar/launch.sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           7

bspc config split_ratio          0.6
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc rule -a Gimp desktop='^8' state=floating follow=on
