vim.g.mapleader=" "

vim.cmd("nnoremap <Leader>v <C-W>v")
vim.cmd("nnoremap <Leader>s <C-W>s")
vim.cmd("nnoremap <Leader>l <C-W>l")
vim.cmd("nnoremap <Leader>j <C-W>j")
vim.cmd("nnoremap <Leader>k <C-W>k")
vim.cmd("nnoremap <Leader>h <C-W>h")
vim.cmd("nnoremap <Leader>L <C-W>L")
vim.cmd("nnoremap <Leader>J <C-W>J")
vim.cmd("nnoremap <Leader>K <C-W>K")
vim.cmd("nnoremap <Leader>H <C-W>H")
vim.cmd("nnoremap <Leader>o <C-W>o")
vim.cmd("nnoremap <Leader><bar> <C-W><bar>")
vim.cmd("nnoremap <Leader>_ <C-W>_")
vim.cmd("nnoremap <Leader>t gt")
vim.cmd("nnoremap <Leader>T gT")
